### ISSUE TITLE
Fix DRY issues with CSS

### ISSUE THREAD

**Issue by chloetruax** [ebecker03/Company-Website#3]
You're reusing declarations such as `position: relative;` and `display: flex;` try to split this out of the main declarations and create helper classes such as: 
``` CSS
    .relative-pos{
        position: relative;
    }
```
and then add them on the needed HTML.
